### ISSUE TITLE
Supporting newer version of engineyard-serverside-adapter

### ISSUE THREAD

**Issue by compactcode** [engineyard/engineyard#191]
Hi,

We would like to user a newer version (2.4.0) of the engineyard-serverside-adapter gem which fixes a release cleanup bug we are seeing. Currently we cannot do this because the gemspec is [locked at version (2.2.0)](https://github.com/engineyard/engineyard/blob/master/engineyard.gemspec#L29), is there a reason for this?

**Comment by martinemde** [comment]
I think this is an oversight. The newer versions mostly provided for features needed in the cloud dashboard so I never upgraded. I'll bump the dep on the next one and leave it looser so future 2.x versions work as well (we follow semver pretty closely so this is just overly restrictive).

Thank you for pointing this out. [3.1.3 is now released with this fix.](https://github.com/engineyard/engineyard/releases/tag/v3.1.3)
